
/*
 * What are the revenue generated by Male vs Female customer?
 */

SELECT
c.gender,
SUM(c.purchase_amount) AS totla_revene
FROM customer c
GROUP BY C.gender;

/*
* Which customers used a discount but still spend more than average purchased amount?
 */

SELECT
c.customer_id,
c.purchase_amount
FROM customer c
WHERE c.discount_applied = 'Yes' AND c.purchase_amount > (SELECT AVG(purchase_amount) FROM customer);

/*
 * Which are the top 5 products with highest average rating?
 */

SELECT
c.item_purchased,
ROUND(AVG(c.review_rating::NUMERIC), 2) AS average_rating 
FROM customer c
GROUP BY C.item_purchased 
ORDER BY average_rating DESC
LIMIT 5;

/*
 * Compare the average purchsed amount between stnadard and express shiping
 */
SELECT 
ROUND(AVG(c.purchase_amount), 2) AS average_purchased_amount,
c.shipping_type 
FROM customer c 
WHERE c.shipping_type IN ('Standard', 'Express')
GROUP BY c.shipping_type
ORDER BY average_purchased_amount DESC;

/*
 *  Do subscribed customer spend more? Compare average and total revenue between 
 * subscriber and non-subscriber
*/

SELECT
COUNT(c.customer_id) AS total_customer,
ROUND(AVG(c.purchase_amount), 2) AS average_purchased_amount,
ROUND(SUM(c.purchase_amount), 2) AS total_purchased_amount,
c.subscription_status
FROM customer c 
GROUP BY c.subscription_status
ORDER BY total_purchased_amount DESC,
		 average_purchased_amount DESC;
/*
 * Which 5 products have the highest percentage of purchases with discount applied?
 */

SELECT
c.item_purchased,
ROUND(100 * SUM(CASE WHEN c.discount_applied = 'Yes' THEN 1 ELSE 0 END)/ COUNT(*), 2) AS percentage_purchased
FROM customer c 
GROUP BY c.item_purchased
ORDER BY percentage_purchased DESC
LIMIT 5;


/*
 * Segment customer into new, returning and loal based on their previous purchased
 *  and show the count on each segment
 */

WITH customer_segment AS (
	SELECT 
	c.customer_id,
	c.previous_purchases,
	CASE WHEN c.previous_purchases = 1 THEN 'New'
		WHEN c.previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		WHEN c.previous_purchases > 10 THEN 'Loyal'
		END AS segment
	FROM customer c 
)
SELECT
segment,
COUNT(*) total_customer
FROM customer_segment
GROUP BY segment
ORDER BY total_customer DESC;

/*
 * What are the top 3 most puchased product on each category
 */

WITH product_performace AS (
 SELECT 
 c.item_purchased,
 c.category,
 COUNT(c.customer_id) total_order,
 ROW_NUMBER() OVER(PARTITION BY c.category ORDER BY COUNT(c.customer_id) DESC) AS customer_ranking
 FROM customer c 
 GROUP BY c.category,  c.item_purchased
) SELECT * FROM product_performace
  WHERE customer_ranking <= 3;


/*
 * Are customer who are repeat buyers( more than 5 previous purchased ) also likely to subscribe?
 */

SELECT
c.subscription_status,
COUNT(c.customer_id) AS repeat_buyer
FROM customer c
WHERE c.previous_purchases > 5
GROUP BY C.subscription_status;

/*
 * What are the revenue contribution of different age groups?
 */

SELECT 
c.age_group,
SUM(c.purchase_amount) AS revenue
FROM customer c 
GROUP BY c.age_group
ORDER BY revenue DESC;

